### ISSUE TITLE
panic with git bug termui

### ISSUE THREAD

**Issue by jedahan** [MichaelMure/git-bug#282]
latest dev with go get on linux

```
▲ ~/src/tldr git bug user create                                   ⇡ cargo-doc  44m ⬢
Name [Jonathan Dahan]: jedahan
Email [hi@jonathan.is]:
Avatar URL: http://example.com

9b02b7ce6b5c46c3cb135e50b890ee52bae72d8d
▲ ~/src/tldr git bug termui                                       8s  ⇡ cargo-doc   ⬢
panic: interface conversion: error is *errors.errorString, not *errors.Error

goroutine 1 [running]:
github.com/MichaelMure/git-bug/termui.Run(0xc00018ad80, 0xc000131f30, 0xc00018ad80)
	/home/micro/.cache/go/src/github.com/MichaelMure/git-bug/termui/termui.go:70 +0x3e0
github.com/MichaelMure/git-bug/commands.runTermUI(0x11a2ee0, 0x11ca798, 0x0, 0x0, 0x0, 0x0)
	/home/micro/.cache/go/src/github.com/MichaelMure/git-bug/commands/termui.go:18 +0xdc
github.com/MichaelMure/git-bug/vendor/github.com/spf13/cobra.(*Command).execute(0x11a2ee0, 0x11ca798, 0x0, 0x0, 0x11a2ee0, 0x11ca798)
	/home/micro/.cache/go/src/github.com/MichaelMure/git-bug/vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/MichaelMure/git-bug/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x11a1d60, 0x0, 0x0, 0x0)
	/home/micro/.cache/go/src/github.com/MichaelMure/git-bug/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/MichaelMure/git-bug/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/micro/.cache/go/src/github.com/MichaelMure/git-bug/vendor/github.com/spf13/cobra/command.go:864
github.com/MichaelMure/git-bug/commands.Execute()
	/home/micro/.cache/go/src/github.com/MichaelMure/git-bug/commands/root.go:54 +0x2d
main.main()
	/home/micro/.cache/go/src/github.com/MichaelMure/git-bug/git-bug.go:17 +0x20
```

**Comment by MichaelMure** [comment]
Were you doing something specific in the termui or just launching it ?

**Comment by jedahan** [comment]
just launching

**Comment by MichaelMure** [comment]
https://github.com/MichaelMure/git-bug/commit/fc568209f073b9d775a09e0dbb8289cf9e5749bf should fix the crash but you most likely have another error. Could you let me know what that is ?

**Comment by jedahan** [comment]
```
Error: termbox: error while reading terminfo data: bytes.Reader.Seek: negative position
```

I am on alacritty, `TERM=alacritty` in env

**Comment by jedahan** [comment]
I used `sudo tic -xe alacritty,alacritty-direct extra/alacritty.info` and now it works :)

**Comment by MichaelMure** [comment]
any idea what the difference would be ?

**Comment by jedahan** [comment]
my terminfo was set to alacritty, but i didnt have that info installed (or in tic, whatever that is).

I think sometimes, software will fallback to something like xterm-256color or just xterm
