### ISSUE TITLE
panic: invalid person data

### ISSUE THREAD

**Issue by devinrsmith** [MichaelMure/git-bug#350]
Running `git bug ls` against this repository is panicking as follows:
 
```
$ ~/bin/git-bug ls
...
panic: invalid person data

goroutine 1 [running]:
github.com/MichaelMure/git-bug/cache.LegacyAuthorExcerpt.DisplayName(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/michael/dev/git-bug/cache/bug_excerpt.go:60 +0x190
github.com/MichaelMure/git-bug/commands.runLsBug(0x1e1c520, 0x1e45678, 0x0, 0x0, 0x0, 0x0)
        /home/michael/dev/git-bug/commands/ls.go:66 +0xd05
github.com/spf13/cobra.(*Command).execute(0x1e1c520, 0x1e45678, 0x0, 0x0, 0x1e1c520, 0x1e45678)
        /home/michael/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x1e1cd00, 0x0, 0x0, 0x0)
        /home/michael/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /home/michael/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
github.com/MichaelMure/git-bug/commands.Execute()
        /home/michael/dev/git-bug/commands/root.go:54 +0x2d
main.main()
        /home/michael/dev/git-bug/git-bug.go:17 +0x20
```

```
$ ~/bin/git-bug version
git-bug version: 0.7.0
```

```
$ git --version
git version 2.25.0
```

```
$ git remote -v
origin  https://github.com/MichaelMure/git-bug.git (fetch)
origin  https://github.com/MichaelMure/git-bug.git (push)
```

**Comment by MichaelMure** [comment]
*sight*

Fixed with https://github.com/MichaelMure/git-bug/commit/e0a702f41d844cef3e0d7bd0f9e986408fdfbe9a

You will have to delete `.git/git-bug/identity-cache` and `.git/git-bug/bug-cache` so the cache is reconstructed.
