### ISSUE TITLE
invalid tree, missing the root entry > git-bug-migration > unknown cache format version 4

### ISSUE THREAD

**Issue by dtrckd** [MichaelMure/git-bug#911]
Hi,

After upgrading to git-bug (v0.7.2) , I got the following error : 

    $ git bug ls
    invalid tree, missing the root entry

I then tried to run git-bug-migration (v0.3.1)

I got the following errors

```
$ git-bug-migration --for-real
Migration #1
Purpose: Convert legacy identities into a complete data structure in git

skipping identity, already updated
got error when reading bug, assuming data is already migrated: "invalid tree, missing the root entry"
got error when reading bug, assuming data is already migrated: "invalid tree, missing the root entry"


Migration #2
Purpose: Migrate bridge credentials from the global git config to a keyring



Migration #3
Purpose: Make bug and identities independent from the storage by making the ID generation self-contained. Also, migrate to the new full DAG entity data model.

skipping bug, already updated
got error when reading bug, assuming data is already migrated: "invalid tree, missing the root entry"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaa4f75]

goroutine 1 [running]:
github.com/MichaelMure/git-bug-migration/migration3/after/identity.(*Identity).Id(...)
        /home/dtrckd/src/i/git-bug-migration/migration3/after/identity/identity.go:478
github.com/MichaelMure/git-bug-migration/migration3/after/identity.SetUserIdentity({0x7fe94137a8a0, 0xc000189c20}, 0x0)
        /home/dtrckd/src/i/git-bug-migration/migration3/after/identity/identity_user.go:15 +0x35
github.com/MichaelMure/git-bug-migration/migration3.(*Migration3).migrate(0xc0001c6550, {0xd69710, 0xc000414480}, {0xd6aba8, 0xc000189c20})
        /home/dtrckd/src/i/git-bug-migration/migration3/migration3.go:110 +0xa12
github.com/MichaelMure/git-bug-migration/migration3.(*Migration3).Run(0xd42ca0, {0xc0001c6550, 0x41})
        /home/dtrckd/src/i/git-bug-migration/migration3/migration3.go:36 +0x8e
main.runRootCmd(0xc00040c6c0, {0xc8}, {0xc00040c6f0, 0x3, 0x0})
        /home/dtrckd/src/i/git-bug-migration/root.go:76 +0x383
main.NewRootCommand.func1(0xc0001b8580, {0xc57a5e, 0x1, 0x1})
        /home/dtrckd/src/i/git-bug-migration/root.go:44 +0x31
github.com/spf13/cobra.(*Command).execute(0xc0001b8580, {0xc000032070, 0x1, 0x1})
        /home/dtrckd/.go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b8580)
        /home/dtrckd/.go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/dtrckd/.go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/dtrckd/src/i/git-bug-migration/main.go:6 +0x1e

```

Same error if I repeat that command. After that crash, the error with git-bug changed, it is now like this:

    $ git bug ls
    Error: unknown cache format version 4

Am I doing something wrong ?

**Comment by MichaelMure** [comment]
Sorry for the late reply.
Migration3 is to migrate to the future version of git-bug (coming soon), so that doesn't apply to you. Unfortunately, it seems like the migration tool get confused about something and crash, which leave the cache in the incorrect format. You can simply delete the `.git/git-bug` folder and it should be regenerated.
